apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: princerajendran/todo-backend:1.0
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: DATABASE_URL
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: SECRET_KEY
        - name: JWT_ALGORITHM
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: JWT_ALGORITHM
        - name: CORS_ALLOWED_ORIGINS
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: CORS_ALLOWED_ORIGINS
        - name: APP_PORT
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: APP_PORT
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: todo-secrets
              key: DEBUG
